INSERT INTO ProductType(ProductTypeName, ProductTypeDesc) VALUES('Mobile','All kind of Mobile Products')
INSERT INTO ProductType(ProductTypeName, ProductTypeDesc) VALUES('Tab','All kind of Tab Products')
INSERT INTO ProductType(ProductTypeName, ProductTypeDesc) VALUES('Laptop','All type of Laptops')
INSERT INTO ProductType(ProductTypeName, ProductTypeDesc) VALUES('Desktop','All type of Desktops')
INSERT INTO Product(ProductTypeId, ProductName, ProductDesc, ProductPrice) VALUES((SELECT ProductTypeId FROM ProductType WHERE ProductTypeName = 'Mobile'), 'Samsung S7', 'Samsung S7 mobile', 30000.00)
INSERT INTO Product(ProductTypeId, ProductName, ProductDesc, ProductPrice) VALUES((SELECT ProductTypeId FROM ProductType WHERE ProductTypeName = 'Tab'), 'Galaxy Tab A', 'Samsung Galaxy Tab', 32000.00)
INSERT INTO Product(ProductTypeId, ProductName, ProductDesc, ProductPrice) VALUES((SELECT ProductTypeId FROM ProductType WHERE ProductTypeName = 'Laptop'), 'Lenovo Yoga', 'Lenovo Laptop', 35340.00)
INSERT INTO Product(ProductTypeId, ProductName, ProductDesc, ProductPrice) VALUES((SELECT ProductTypeId FROM ProductType WHERE ProductTypeName = 'Desktop'), 'Dell Optiplex', 'Dell Desktop', 24800.00)
INSERT INTO Product(ProductTypeId, ProductName, ProductDesc, ProductPrice) VALUES((SELECT ProductTypeId FROM ProductType WHERE ProductTypeName = 'Desktop'), 'Samsung 18.5 Slim', 'Samsung Desktop', 5010.00)